# Generated by Django 4.0.1 on 2022-02-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
    ]
